### PR TITLE
Release/TR-731 old media height fix

### PR DESCRIPTION
**Pull request by meefox**
Update @oat-sa/tao-core-ui to 1.22.5

### CODE REVIEW

**Review by jsconan — APPROVED** [review]
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

**Review by wazelin — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

**Comment by wazelin** [comment]
A note for the future PRs.

It _should_ have at least one semantic commit message. Your initial commit message was `chore: update version @oat-sa/tao-core-ui to 1.22.5`. Does it count as a fix-version bump or any other?

I suppose, it's better to be a bit more specific and stick to either `fix` or `feature` in most of the cases. That version was updated to provide a `fix`.

**Comment by meefox** [comment]
> A note for the future PRs.
> 
> It _should_ have at least one semantic commit message. Your initial commit message was `chore: update version @oat-sa/tao-core-ui to 1.22.5`. Does it count as a fix-version bump or any other?
> 
> I suppose, it's better to be a bit more specific and stick to either `fix` or `feature` in most of the cases. That version was updated to provide a `fix`.

actually according to https://oat-sa.atlassian.net/wiki/spaces/DEV/pages/872775905/Conventional+Commits chore is for version update, no code changes, sure it will use a newer version though.

**Comment by btamas** [comment]
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Pull request merged**
