### PR TITLE
Fix/TR-5205/Wrong type for the pagesize

### PR DESCRIPTION
**Pull request by jsconan**
### Related to: https://oat-sa.atlassian.net/browse/TR-5205

Requires: 
 - [x] https://github.com/oat-sa/tao-core-ui-fe/pull/546

### Summary

Fix an issue with the pageSizeSelector in relation to the datatable component.

### Details

Update the internal lib tao-core-ui with the proper patch.

See [companion PR](https://github.com/oat-sa/tao-core-ui-fe/pull/546) for mode details.

### How to test
- install the fix: `cd tao/views && npm i`
- follow the instruction in the ticket

**TODO**
- [ ] Update package.json with released version

### CODE REVIEW

**Review by shaveko — APPROVED** [review]
Looks good, version of `@oat-sa/tao-core-ui` should be updated of course to release before merging 

- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Review by hectoras — APPROVED** [review]

**Review by hectoras — COMMENTED** [review]
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Target branch is correct
- [x] Update logs provided
- [x] Commits are following conventional commits
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Kitchen links are not exposed in the description
- [x] Run composer locally is working
- [x] Updated instance with old composer works
- [x] No unnecessary dependencies are installed

**Review by rgomeztao — APPROVED** [review]
all good, i guess :thinking: just to confirm that this is for testing and not for releasing, since i can see that were not updating for a new version but for a certain branch :)

**Comment by jsconan** [comment]
> all good, i guess 🤔 just to confirm that this is for testing and not for releasing, since i can see that were not updating for a new version but for a certain branch :)

Yes, this is the usual process for having the dependencies installed with the linked PRs. It allows having the full feature installed. Then, the version is set once the companion PR has been merged, and only then we can merge this PR.

This is now the case: https://github.com/oat-sa/tao-core/pull/3765/commits/fd3d3e6869e09e739b2bfe4b18b4e7073b75f9c7

**Pull request merged**
