### PR TITLE
feature/INV-170/Integrate codemirror

### PR DESCRIPTION
**Pull request by andrey-ponamarev**
**Related to task:**  https://oat-sa.atlassian.net/browse/INV-170
**Description:** The feature is allowed user to edit test in XML format.
To make xml code looks good we want to integrate https://codemirror.net/ 
The integration part is https://github.com/oat-sa/extension-tao-testqti/pull/1843

**Required:** 
- [x] [Release and update package.json for building process](https://github.com/oat-sa/grunt-tao-bundle/pull/16)

### CODE REVIEW

**Comment by tikhanovichA** [comment]
Bump version?

**Comment by krampstudio** [comment]
how is it bundled ? I can see it configured as a package, but can you check in which bundle codemirror will end ? 
I'm asking because I'm wondering this will also impact the bundle size during a delivery

**Comment by andrey-ponamarev** [comment]
@krampstudio on the attached image you can find the sizes of loaded assets (included autocomplete add-ons for the next steps).
The size of the npm package is 3,5 MB
The whole code is bundled and build by library
Screenshot 2020-06-18 at 13 36 26

**Comment by andrey-ponamarev** [comment]
@jsconan after discussion with @btamas we decided that the proper place for it tao node_modules.
The code from the library will not be added to the bundle it will be stayed and serves from node_modules

**Comment by krampstudio** [comment]
> @jsconan after discussion with @btamas we decided that the proper place for it is tao node_modules.
> The code from the library will not be added to the bundle it will be stayed and serves from node_modules and it will be loaded only when it's required

code in node_modules might not be loaded in production (bundles are sent to CDN, not node_modules)

**Comment by andrey-ponamarev** [comment]
Dear @jsconan and @krampstudio here is [PR for grunt-tao-bundle](https://github.com/oat-sa/grunt-tao-bundle/pull/16) to bundle packages.
~300kb is added to the bundle size.
 codemirror included | without lib
------------ | -------------
Screenshot 2020-07-01 at 13 07 37 | Screenshot 2020-07-01 at 13 08 22

**Comment by jsconan** [comment]
This is annoying the bundle doubled its size. I know this is for the backoffice, and the delivery should not be impacted, but this might still be an issue.
Moreover, we might have loading issues if other extensions also use the same lib (extension requiring the same lib, but in another bundle).
Could you consider adding a dedicated bundle for the lib?

**Comment by alexeyvy** [comment]
**Review Checklist**
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Pull request merged**
