### PR TITLE
add builder to composer

### PR DESCRIPTION
**Pull request by llecaque**

### CODE REVIEW

**Comment by llecaque** [comment]
retest this please

**Comment by llecaque** [comment]
retest this please

**Comment by llecaque** [comment]
retest this please

**Comment by llecaque** [comment]
retest this please

**Comment by llecaque** [comment]
retest this please

**Comment by llecaque** [comment]
retest this please

**Comment by llecaque** [comment]
retest this please

**Comment by siwane** [comment]
retest this please

**Comment by llecaque** [comment]
retest this please

**Comment by llecaque** [comment]
retest this please

**Comment by llecaque** [comment]
retest this please

**Comment by llecaque** [comment]
retest this please

**Comment by llecaque** [comment]
retest this please

**Comment by llecaque** [comment]
retest this please

**Comment by llecaque** [comment]
retest this please

**Comment by llecaque** [comment]
retest this please

**Comment by llecaque** [comment]
retest this please

**Comment by llecaque** [comment]
retest this please

**Comment by llecaque** [comment]
retest this please

**Comment by llecaque** [comment]
retest this please

**Pull request merged**
