### PR TITLE
Tao 606 security constraints configuration

### PR DESCRIPTION
**Pull request by boajer**

### CODE REVIEW

**Comment by bugalot** [comment]
Hello there!

When I set the 'upper' configuration parameter to true, I can create test takers with non-uppercase passwords.

**Comment by boajer** [comment]
Hi! 
I fixed it in related PR https://github.com/oat-sa/generis/pull/57

**Comment by bugalot** [comment]
Hello there !

When installing, using the following password information for the super user:

login: admin
password: admin

I get the following error after clicking the "install" button (last step) and a bit of processing:

"Password must be: This field is too short (minimum 4),Must include at least one letter,Must include lower case letters in /home/jerome/dev/taotrunk300/tao/install/class.Installator.php at line 439"

However, "admin" has a length of 5, contains at least one letter, ans include lower case letters ;) !

**Comment by boajer** [comment]
Hi, check it please again

**Comment by bugalot** [comment]
I'm currently checking, thanks for your quick response!

**Comment by bugalot** [comment]
Thanks !!!

**Comment by bugalot** [comment]
Dear Michael,

We forgot something! The update script which copies a default version of /generis/passwords.conf.php into the /config folder. Without that, a running installation of TAO which updates its source code will have problems (especially when running test cases). Could you have a look at that?

Thanks!

**Pull request merged**
