### PR TITLE
chore: added leveled japanise translations

### PR DESCRIPTION
**Pull request by boajer**
https://oat-sa.atlassian.net/browse/TR-2296

1. https://github.com/oat-sa/extension-tao-test-runner-plugins/pull/209
2. https://github.com/oat-sa/extension-tao-test/pull/400
3. https://github.com/oat-sa/extension-tao-item/pull/539
4. https://github.com/oat-sa/extension-tao-testqti/pull/2092
5. https://github.com/oat-sa/extension-tao-itemqti/pull/1922
6. https://github.com/oat-sa/extension-tao-itemqti-pic/pull/101
7. https://github.com/oat-sa/extension-tao-delivery/pull/517
8. https://github.com/oat-sa/extension-tao-itemqti-pci/pull/247
9. https://github.com/oat-sa/extension-tao-ltideliveryprovider/pull/294

### CODE REVIEW

**Review by wazelin — CHANGES_REQUESTED** [review]
It may also be beneficial to generate (so far empty) `messages.po` files for each new locale, so that they could later be used in a translation adaptation process.

`php tao/scripts/taoTranslate.php -v -a compile -e tao -l <locale>` should do it if I'm not mistaken.


Also, new locales added is certainly a feature, not a fix. WDYT of bumpting the minor version instead?

**Review by quintanilhar — CHANGES_REQUESTED** [review]
@wazelin made some goods points, I can approve right after you can address them. :)

**Review by wazelin — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

**Review by emgolubev — APPROVED** [review]

**Comment by emgolubev** [comment]
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by poyuki — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Pull request merged**
