### PR TITLE
Feat/tr 3285/update dev dependencies

### PR DESCRIPTION
**Pull request by shaveko**
related https://oat-sa.atlassian.net/browse/TR-3285

### Description

Update dev dependencies 

 ### How to test
run grunt tasks

`npx grunt sassall`
`npx grunt bundleall`
`npx grunt testall`

### CODE REVIEW

**Review by bziondik — CHANGES_REQUESTED** [review]
For me fails `npm i`
image

**Review by jsconan — APPROVED** [review]
Nice work!

All good for me, it installs well, and the grunt tasks are still working fine.

Moving from:
```
found 24 vulnerabilities (1 low, 6 moderate, 14 high, 3 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

To:
```
found 8 vulnerabilities (3 moderate, 3 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Review Checklist**
- [ ] ~~New code is covered by tests (if applicable)~~
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] ~~New code is not subject to concurrency issues (if applicable)~~
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic

**Comment by jsconan** [comment]
@bziondik your `Node.js` is outdated. You need to update to `Node.js 14`

**Review by bziondik — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

Works with node v14

**Pull request merged**
