### PR TITLE
Merge develop into TAO-10203-advanced-search

### PR DESCRIPTION
**Pull request by 404passionFruit**
There were conflicts in css files that required running a build script

### CODE REVIEW

**Review by bartlomiejmarszal — APPROVED** [review]
This merge is causing issues with taoMediaManager. 
In our instances we fixed all not related extensions versions. 
In order to make it work we need to update taoMediaManager to version:
`11.7.0` or `dev-develop`

Unit tests are already broken in `feature/TAO-10203-advanced-search`

**Comment by bziondik** [comment]
> This merge is causing issues with taoMediaManager.
> In our instances we fixed all not related extensions versions.
> In order to make it work we need to update taoMediaManager to version:
> `11.7.0` or `dev-develop`
> 
> Unit tests are already broken in `feature/TAO-10203-advanced-search`

@bartlomiejmarszal After updating just taoMediaManager I had problem with  oat-sa/composer-npm-bridge versions
```
Problem 1
    - Installation request for oat-sa/tao-core dev-Merge/develop-into-TAO-10203-advanced-search as 46.1.0 -> satisfiable by oat-sa/tao-core[dev-Merge/develop-into-TAO-10203-advanced-search].
    - Installation request for oat-sa/lib-tao-elasticsearch dev-feature/CON-76/advance-search-in-result-page as 2.1.0 -> satisfiable by oat-sa/lib-tao-elasticsearch[dev-feature/CON-76/advance-search-in-result-page].
    - Conclusion: don't install oat-sa/tao-core 46.1.0|remove oat-sa/composer-npm-bridge 0.3.0
    - Conclusion: don't install oat-sa/tao-core 46.1.0|remove oat-sa/extension-tao-testqti v39.5.1
    - Conclusion: install oat-sa/tao-core 46.1.0
    - oat-sa/tao-core 46.1.0 requires oat-sa/composer-npm-bridge ~0.4.2||dev-master -> satisfiable by oat-sa/composer-npm-bridge[0.4.2, dev-master].
    - Can only install one of: oat-sa/composer-npm-bridge[0.4.2, 0.3.0].
    - Can only install one of: oat-sa/composer-npm-bridge[dev-master, 0.3.0].
    - oat-sa/extension-tao-testqti v39.5.1 requires oat-sa/composer-npm-bridge ^0.3.0 -> satisfiable by oat-sa/composer-npm-bridge[0.3.0].
    - Installation request for oat-sa/extension-tao-testqti 39.5.1 -> satisfiable by oat-sa/extension-tao-testqti[v39.5.1].
```
When I updated all extensions to "dev-develop" except `"oat-sa/extension-tao-dac-simple": "dev-feature/TAO-10203-advanced-search",` this was fixed

**Comment by bziondik** [comment]
@bartlomiejmarszal Have an error on request `tao/Search/search` after fresh install
image

**Review by bartlomiejmarszal — COMMENTED** [review]
This PR will require that all developers will have to change their docker-environments to this [PR](https://github.com/oat-sa/docker-advance-search/pull/5)

**Review by bziondik — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Pull request merged**
