### PR TITLE
[Feature] ADF-39 - Text wrap pictures

### PR DESCRIPTION
**Pull request by 404passionFruit**
Cherry-picked solution from https://github.com/oat-sa/tao-core/pull/2804

**Jira**
https://oat-sa.atlassian.net/browse/ADF-39

**Other PRs**
https://github.com/oat-sa/tao-core-ui-fe/pull/302
https://github.com/oat-sa/extension-tao-itemqti/pull/1761
https://github.com/oat-sa/extension-tao-mediamanager/pull/277
https://github.com/oat-sa/extension-tao-devtools/pull/188

**Environment**
Deployed to the playground, the link is in the ticket

### CODE REVIEW

**Review by habemuscode — CHANGES_REQUESTED** [review]
Don't push JS bundles ( `vendor.min.js.map` )

**Review by clagosarias — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

**Review by habemuscode — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Comment by habemuscode** [comment]
Closed in favor of https://github.com/oat-sa/tao-core/pull/2941

**Pull request closed without merging**
