### PR TITLE
chore(version): bump tao-core-ui-fe version

### PR DESCRIPTION
**Pull request by adriloma**
**related to:** https://oat-sa.atlassian.net/browse/TAO-10457

Just bumps `tao-core-ui` to its latest version. No `manifest` version update as target branch is a feature branch.

### CODE REVIEW

**Review by bziondik — CHANGES_REQUESTED** [review]
Add also new version in manifest

**Review by bziondik — APPROVED** [review]
Version in manifest will be changed in the target branch

**Review by andreluizmachado — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by andreluizmachado — CHANGES_REQUESTED** [review]
Build is failing

**Review by andreluizmachado — APPROVED** [review]

**Pull request merged**
