### PR TITLE
Update npm-bridge up to new version

### PR DESCRIPTION
**Pull request by Alroniks**
Work under [CGF-22](https://oat-sa.atlassian.net/browse/CGF-22)

Before merging following pull requests should be merged too:
https://github.com/oat-sa/extension-tao-itemqti/pull/1582
https://github.com/oat-sa/extension-tao-item/pull/439
https://github.com/oat-sa/extension-tao-testqti/pull/1939
https://github.com/oat-sa/extension-tao-test/pull/357

### CODE REVIEW

**Review by AndreyNegrov — APPROVED** [review]
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`

**Review by SashaTAO — CHANGES_REQUESTED** [review]
It looks like we have some dependencies which require PHP 7.4 for Composer 2 (executed on PHP 7.25, Composer 2):
``` 
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - ocramius/package-versions[1.6.0, ..., 1.9.x-dev] require php ^7.4.0 -> your php version (7.2.25) does not satisfy that requirement.
    - ocramius/package-versions[1.10.0, ..., 1.11.x-dev] require php ^7.4.7 -> your php version (7.2.25) does not satisfy that requirement.
    - ocramius/package-versions[1.3.0, ..., 1.4.2] require composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - ocramius/package-versions[1.5.0, ..., 1.5.1] require php ^7.3.0 -> your php version (7.2.25) does not satisfy that requirement.
    - oat-sa/tao-core dev-fix/CGF-22_npm_bridge_new_version requires doctrine/migrations 3.0.1 -> satisfiable by doctrine/migrations[3.0.1].
    - doctrine/migrations 3.0.1 requires ocramius/package-versions ^1.3 -> satisfiable by ocramius/package-versions[1.3.0, ..., 1.11.x-dev].
    - Root composer.json requires oat-sa/tao-core dev-fix/CGF-22_npm_bridge_new_version -> satisfiable by oat-sa/tao-core[dev-fix/CGF-22_npm_bridge_new_version].
ocramius/package-versions only provides support for Composer 2 in 1.8+, which requires PHP 7.4.

**Review by bartlomiejmarszal — CHANGES_REQUESTED** [review]
I have similar error when composer update
```  Problem 1
    - ocramius/package-versions[1.6.0, ..., 1.9.x-dev] require php ^7.4.0 -> your php version (7.3.11) does not satisfy that requirement.
    - ocramius/package-versions[1.10.0, ..., 1.11.x-dev] require php ^7.4.7 -> your php version (7.3.11) does not satisfy that requirement.
    - ocramius/package-versions[1.3.0, ..., 1.5.1] require composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - oat-sa/tao-core dev-fix/CGF-22_npm_bridge_new_version requires doctrine/migrations 3.0.1 -> satisfiable by doctrine/migrations[3.0.1].
    - doctrine/migrations 3.0.1 requires ocramius/package-versions ^1.3 -> satisfiable by ocramius/package-versions[1.3.0, ..., 1.11.x-dev].
    - Root composer.json requires oat-sa/tao-core dev-fix/CGF-22_npm_bridge_new_version -> satisfiable by oat-sa/tao-core[dev-fix/CGF-22_npm_bridge_new_version].```

**Comment by Alroniks** [comment]
So, the problem was that author Ocramius did something that sometimes happens but it shouldn't.
The latest versions of his code require PHP 7.4 at least, that OK in an ideal world, but does not work in the business.
The composer team [made the fork of his library](https://github.com/composer/package-versions-deprecated) (see readme) and recommend using that one. Also, this package comes to us from Doctrine Migrations, where [people also recommend](https://github.com/doctrine/migrations/issues/1066#issuecomment-716507545) to use the suggested fork.

I've added a dependency to tao-core, which should fix issues with updating on Composer 2.0 and PHP 7.2.

@SashaTAO and @bartlomiejmarszal Could you please check again if it works?

**Review by SashaTAO — APPROVED** [review]
Approved.

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Code is self documented

**Pull request merged**
