### PR TITLE
Fix/adf 508/cypress form flickering

### PR DESCRIPTION
**Pull request by 404passionFruit**
**Jira**
https://oat-sa.atlassian.net/browse/ADF-508

**The fix**
Clear content block before sending the request for `subClass`

**Bonus**
Added `wait` in class delete test helper to guarantee that the app is ready to open confirmation modal. The issue with cypress not catching the modal is not related directly to the fix, however appeared several times on my local machine while I was working on the ticket. For better understanding the issue with the modal we can create a tech debt ticket if needed. 

**How to test the fix**
Test locally with cypress, make sure the https://github.com/oat-sa/extension-tao-item is up to date with `develop` on your local env

**How to test for regressions**
// TODO: Kitchen env link is in the ticket

### CODE REVIEW

**Review by AnastasiaArcadia — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Review by clagosarias — APPROVED** [review]
- [x] New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [ ]  New code is not subject to concurrency issues (if applicable)
- [x]  The feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request's target is not master
- [x]  Pull request title and description are meaningful
- [x]  Commits are following conventional commits
- [x]  Kitchen links are not exposed in the description

**Review by habemuscode — APPROVED** [review]
- [x] New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [ ]  New code is not subject to concurrency issues (if applicable)
- [ ]  The feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request's target is not master
- [x]  Pull request title and description are meaningful
- [x]  Commits are following conventional commits
- [x]  Kitchen links are not exposed in the description

**Review by bziondik — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Pull request merged**
