### PR TITLE
Feature/ADF-740 e2e generis search

### PR DESCRIPTION
**Pull request by meefox**
Added Generis search E2E test case

- Checkout the branch tao core https://github.com/oat-sa/tao-core/pull/3314
- Checkout tao Items branch https://github.com/oat-sa/extension-tao-item/pull/555
- Run `npm run cy:open` from the ./tao/views
- Select tao/views/cypress/tests/search-generis.spec.js
- Made some coffee and see all 8 test cases being green
Screenshot 2022-01-06 at 17 24 04

### CODE REVIEW

**Review by bziondik — CHANGES_REQUESTED** [review]
1. `views/cypress/tests/generis-search.spec.js` and `views/cypress/tests/search-generis.spec.js` is the same?
2. search for items should be in `taoItems`, there are all selectors for this

**Comment by meefox** [comment]
> * `views/cypress/tests/generis-search.spec.js` and `views/cypress/tests/search-generis.spec.js` is the same?
> * search for items should be in `taoItems`, there are all selectors for this

1) It should be only search-generis.spec.js I did rename it in order to group better with the upcoming test for advanced search.
2) I saw it there but I am not sure it will be a good idea to introduce dependency from another extension

**Review by Silvia-loza — APPROVED** [review]
All test pass consistently and code looks good.
From my side with refence to the comments above about location, both arguments have valid points... not sure what's best way to proceed in that sense... 
- [X] New code is covered by tests (if applicable)
- [X] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [X]  Pull request's target is not` master`
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

image

**Review by clagosarias — APPROVED** [review]
- [x] New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  The feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request's target is not master
- [x]  Pull request title and description are meaningful
- [x]  Commits are following conventional commits
- [x]  Kitchen links are not exposed in the description

**Review by Silvia-loza — APPROVED** [review]
- [X] New code is covered by tests (if applicable)
- [X] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [X]  Pull request's target is not` master`
- [X] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

**Review by clagosarias — APPROVED** [review]
- [x] New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  The feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request's target is not master
- [x]  Pull request title and description are meaningful
- [x]  Commits are following conventional commits
- [x]  Kitchen links are not exposed in the description

**Pull request merged**
