### PR TITLE
Backport/adf 797/multilevel dependencies

### PR DESCRIPTION
**Pull request by clagosarias**
https://oat-sa.atlassian.net/browse/ADF-797

Backport of https://github.com/oat-sa/tao-core/pull/3236

### CODE REVIEW

**Review by andreluizmachado — APPROVED** [review]
LGTM

**Review by Silvia-loza — COMMENTED** [review]
Would we not require to add js bundles to this backport?
Everything else LGTM.

**Review by bziondik — CHANGES_REQUESTED** [review]
Add js bundles, please

**Review by bziondik — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Pull request merged**
