### PR TITLE
chore: version bump

### PR DESCRIPTION
**Pull request by meefox**
Related to https://oat-sa.atlassian.net/browse/TR-893 (2/3)

Add RTL/LTR for choice interaction

Install
https://oat-sa.atlassian.net/browse/TR-893?focusedCommentId=144298

Required 
https://github.com/oat-sa/extension-tao-itemqti/pull/1830 

Depends
https://github.com/oat-sa/tao-core-ui-fe/pull/330/files

### CODE REVIEW

**Review by andrey-ponamarev — APPROVED** [review]
⚠️ BEFORE MERGE UPDATE `package*.json` files with correct version

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`
- [x] Pull request title and description are meaningful
- [x] Commits are following conventional commits

**Comment by andrey-ponamarev** [comment]
@meefox Could you check CI errors or ask someone to take a look

**Comment by meefox** [comment]
> @meefox Could you check CI errors or ask someone to take a look

Seems to me like PHP UT failing.

**Review by bziondik — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful
image

**Pull request merged**
