### PR TITLE
fix: tr-296 fix scrollbars behavior for zoom (MSIE) in fullscreen mode

### PR DESCRIPTION
**Pull request by lecosson**
Related to:
- https://oat-sa.atlassian.net/browse/TR-296

vertical scrollbar added to page on zoom in fullscreen mode for MSIE

How to check:
- set `DEBUG_MODE` to  `false` in `config/generis.conf.php`
- check delivery in fullscreen mode with MSIE11, try to use zoom and ensure test runner controls are available

### CODE REVIEW

**Review by jsconan — COMMENTED** [review]
It works well.
However, I wonder if this is the right place to put this change, as the `fullscreen` class is set only by the [fullscreen plugin:](https://github.com/oat-sa/extension-tao-test-runner-plugins/blob/8711fea42ad693ce284a9514bbaab01761c55622/views/js/runner/plugins/security/fullScreen.js#L172).

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

**Review by btamas — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

**Comment by lecosson** [comment]
temporary converted to draft to implement requested changes

**Comment by lecosson** [comment]
implemented another way in pr https://github.com/oat-sa/extension-tao-test-runner-plugins/pull/181

**Pull request closed without merging**
