### PR TITLE
Tao 1253 scaler

### PR DESCRIPTION
**Pull request by dietertaotesting**

### CODE REVIEW

**Comment by krampstudio** [comment]
Could you keep only the file `unmatrix.js` (it should also contain a link to it's repository in it's heade, so we can link it to it's author/version).

**Comment by krampstudio** [comment]
There's no need to modify your code, but this is a hint for the next tests cases : 

The function `resetContainer` is not necessary and the fixture is made for that. You could create directly multiple containers : 
```html
<div id="qunit-fixture">
    <div id="container1"></div>
    <div id="container2" class="pre-translate"></div>
    <div id="container2" class="pre-rotate"></div>
    <div id="container2" class="pre-skew"></div>
    <div id="container2" class="pre-scale"></div>
    <div id="container2" class="pre-transform"></div>
</div>
```

And then you can just split your tests and organize them in QUnit modules : 
```javascript
QUnit.module('Translating /  pre-transformed container');
QUnit.test('TranslateX', function (assert) {
         var $container = $('.container2'),
             rect;
 
         transformer.translateX($container, 100);
         rect = getRect($container);
         assert.ok(rect.left === 200, 'translateX(100) on top of existing 100px');
});
QUnit.test('Translate', function (assert) {
         var $container = $('.container2'),
             rect,
             origTop = getRect($container).top;

          transformer.translate($container, 100);
         rect = getRect($container);
        assert.ok(rect.left === 200 && rect.top === origTop + 100, 'translate(100) on top of existing 100px');
});
...
```

**Comment by dietertaotesting** [comment]
Didn't know that - thanks for pointing this out!

**Comment by krampstudio** [comment]
The test case **Transformer: Transform and Reset** doesn't work in webkit based browsers (tried with Chrome 44.0.2403.89 and PhantomJS) : 

```
transform() changes the value of rotate
Expected: 	
20
Source: 	
    at Object.<anonymous> (http://127.0.0.1:8082/tao/views/js/test/ui/transformer/test.js:226:16)
    at Object.Test.run (http://127.0.0.1:8082/tao/views/js/lib/qunit/qunit.js:203:18)
    at http://127.0.0.1:8082/tao/views/js/lib/qunit/qunit.js:361:10
    at process (http://127.0.0.1:8082/tao/views/js/lib/qunit/qunit.js:1453:24)
    at http://127.0.0.1:8082/tao/views/js/lib/qunit/qunit.js:479:5

transform() changes the value of skew
Expected: 	
20
Source: 	
    at Object.<anonymous> (http://127.0.0.1:8082/tao/views/js/test/ui/transformer/test.js:227:16)
    at Object.Test.run (http://127.0.0.1:8082/tao/views/js/lib/qunit/qunit.js:203:18)
    at http://127.0.0.1:8082/tao/views/js/lib/qunit/qunit.js:361:10
    at process (http://127.0.0.1:8082/tao/views/js/lib/qunit/qunit.js:1453:24)
    at http://127.0.0.1:8082/tao/views/js/lib/qunit/qunit.js:479:5

transform() changes the value of scaleX
Expected: 	
1.5
Source: 	
    at Object.<anonymous> (http://127.0.0.1:8082/tao/views/js/test/ui/transformer/test.js:228:16)
    at Object.Test.run (http://127.0.0.1:8082/tao/views/js/lib/qunit/qunit.js:203:18)
    at http://127.0.0.1:8082/tao/views/js/lib/qunit/qunit.js:361:10
    at process (http://127.0.0.1:8082/tao/views/js/lib/qunit/qunit.js:1453:24)
    at http://127.0.0.1:8082/tao/views/js/lib/qunit/qunit.js:479:5

transform() changes the value of scaleY
Expected: 	
1.5
Source: 	
    at Object.<anonymous> (http://127.0.0.1:8082/tao/views/js/test/ui/transformer/test.js:229:16)
    at Object.Test.run (http://127.0.0.1:8082/tao/views/js/lib/qunit/qunit.js:203:18)
    at http://127.0.0.1:8082/tao/views/js/lib/qunit/qunit.js:361:10
    at process (http://127.0.0.1:8082/tao/views/js/lib/qunit/qunit.js:1453:24)
    at http://127.0.0.1:8082/tao/views/js/lib/qunit/qunit.js:479:5
```

**Comment by dietertaotesting** [comment]
Removed offending code

**Pull request merged**
