### PR TITLE
[Fix] CON 122 - Graphic design match mockup

### PR DESCRIPTION
**Pull request by habemuscode**
**Dependency PR**

https://github.com/oat-sa/tao-core-ui-fe/pull/230

**Another related PR**

https://github.com/oat-sa/extension-tao-itemqti/pull/1600

### CODE REVIEW

**Comment by habemuscode** [comment]
Can be tested here: http://playground.kitchen.it.taocloud.org/?p=test-juan_delivery.git;a=summary

**Review by bziondik — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Review by vaultkeeper — APPROVED** [review]
LGFM

**Review by boajer — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

**Pull request merged**
