### PR TITLE
Feature/TR-4862/Unify handlebars helpers

### PR DESCRIPTION
**Pull request by jsconan**
### Dependencies

- [x] https://github.com/oat-sa/tao-core-libs-fe/pull/56
- [x] https://github.com/oat-sa/tao-core-ui-fe/pull/529

### Summary

Use the unified Handlebars integration.

### Details

The `tpl.js` file is responsible for the integration of Handlebars with RequireJS, together with the declaration of the custom helpers for TAO. However, it was duplicated in several places. The purpose of this PR is to have only one place where this integration is made, and allows to replace some of its pieces.

In some places, only the helpers were duplicated, hence the idea of separating them into a dedicated module.
The `tpl.js` contains the RequireJS plugin for compiling the templates on the fly, or adding them into a bundle. With this respect, it generates wrapping bundles containing the compiled template, together with a reference to Handlebars. However, in some cases, it is needed to link the template to a specific version of Handlebars (PCI case). For this reason, the module writer has been split into a dedicated module, which can be replaced using the RequireJS config.

The duplicate is removed from this repository as it is declared into `tao-core-libs`.

### How to test
Install all dependencies, then
- check the Handlebars template still behaves well in debug mode
- check the Handlebars template still behaves well in production mode (using the bundles)

### CODE REVIEW

**Review by shaveko — APPROVED** [review]
Looks good. Checked items are rendered with no issue in debug/production mode

- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Review by oatymart — CHANGES_REQUESTED** [review]
In a fresh TAO install (`release-2022-12` plus these branches),
during `npx grunt connect:test taotest` there is a failure which looks suspicious:

```
Testing http://127.0.0.1:60319/tao/views/js/test/tpl/test.html ......<span></span>
F
>> registered handlers - d4ffad04
>> Message: property helper rendering ok
>> Actual: "<span></span>"
>> Expected: "<span>0</span>"
>> at Object.<anonymous> (http://127.0.0.1:60319/tao/views/js/test/tpl/test.js:79:16)
```

The file being tested has moved to `tao-core-libs`. Should the test be moved there as well? It still runs thanks to the dependency, but something goes wrong.

**Comment by jsconan** [comment]
Thank you Martin! My bad, I did not check again the UT after the move of the lib. I'll put the test aside in the right repo.

**Review by oatymart — APPROVED** [review]
Reduced unit tests are working now. Good job!

**Pull request merged**
