### PR TITLE
chore: update tao-core-ui lib

### PR DESCRIPTION
**Pull request by AnastasiaArcadia**
**Related task:** https://oat-sa.atlassian.net/browse/AUT-1176

**Backport of the fix:** https://oat-sa.atlassian.net/browse/ADF-695

### CODE REVIEW

**Review by bziondik — CHANGES_REQUESTED** [review]
You can't update  "@oat-sa/tao-core-ui" from  "1.32.0" to "1.36.1"
You need first backport changes from https://github.com/oat-sa/tao-core-ui-fe/pull/368 to  "@oat-sa/tao-core-ui" from  "1.32.0"
Then use this new version in tao-core

**Review by bziondik — CHANGES_REQUESTED** [review]
please, add bundles

**Review by bziondik — APPROVED** [review]
LGTM

**Review by clagosarias — APPROVED** [review]
LGTM

**Pull request merged**
