### PR TITLE
[Fix ADF-600]: Delete images receive error

### PR DESCRIPTION
**Pull request by habemuscode**
**Ticket**

https://oat-sa.atlassian.net/browse/ADF-600

**Related PR's**

https://github.com/oat-sa/tao-core-ui-fe/pull/344

### CODE REVIEW

**Review by clagosarias — APPROVED** [review]
LGTM, Remember to update with final version 👍

**Review by AnastasiaArcadia — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not master

**Review by 404passionFruit — APPROVED** [review]

**Comment by 404passionFruit** [comment]
- [ ] New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [ ]  New code is not subject to concurrency issues (if applicable)
- [ ]  The feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request's target is not master
- [x]  Pull request title and description are meaningful
- [x]  Commits are following conventional commits
- [x]  Kitchen links are not exposed in the description

**Comment by AntonNeviarouski** [comment]
QA verified on http://test-gabriel.playground.kitchen.it.taocloud.org:42221/

**Pull request merged**
