### PR TITLE
Added imported resources/uris in return statements

### PR DESCRIPTION
**Pull request by Alroniks**

### CODE REVIEW

**Comment by boajer** [comment]
Could you please increase version of extension?

**Comment by Alroniks** [comment]
@boajer Fixed version

**Comment by boajer** [comment]
As for me it's looks Ok and will not break anything, but let's wait for @jbout  approval.

**Comment by jbout** [comment]
The idea behind the options, was to allow you to customize the import, not to pass back parameters to the caller. Could this be done in the returned report instead, as subreport?

**Comment by Alroniks** [comment]
@jbout I updated pull request and added fix in the test taker extension (linked)

**Pull request merged**
