### PR TITLE
Tao 729 one ck file

### PR DESCRIPTION
**Pull request by ssipasseuth**
Replaced ckeditor lib with the one-file version generated from https://github.com/oat-sa/ckeditor-dev/blob/tao-one-file/dev/builder/oneFile.php

This is related to https://github.com/oat-sa/ckeditor-dev/pull/2

### CODE REVIEW

**Comment by ssipasseuth** [comment]
The result is there is now only one single js files. All the other resources are either css or picture files.
The list of the resources are
{
    "js": [],
    "css": [
        "skins/tao/dialog.css",
        "skins/tao/dialog_ie.css",
        "skins/tao/dialog_ie8.css",
        "skins/tao/dialog_iequirks.css",
        "skins/tao/dialog_opera.css",
        "skins/tao/editor.css",
        "skins/tao/editor_gecko.css",
        "skins/tao/editor_ie.css",
        "skins/tao/editor_ie8.css",
        "skins/tao/editor_iequirks.css",
        "contents.css"
    ],
    "img": [
        "skins/tao/icons-hl.png",
        "skins/tao/icons.png",
        "skins/tao/icons_hidpi-hl.png",
        "skins/tao/icons_hidpi.png",
        "skins/tao/images/arrow.png",
        "skins/tao/images/close.png",
        "skins/tao/images/hidpi/close.png",
        "skins/tao/images/hidpi/lock-open.png",
        "skins/tao/images/hidpi/lock.png",
        "skins/tao/images/hidpi/refresh.png",
        "skins/tao/images/icons.png",
        "skins/tao/images/lock-open.png",
        "skins/tao/images/lock.png",
        "skins/tao/images/refresh.png",
        "plugins/link/images/anchor.png",
        "plugins/link/images/hidpi/anchor.png",
        "plugins/magicline/images/hidpi/icon-rtl.png",
        "plugins/magicline/images/hidpi/icon.png",
        "plugins/magicline/images/icon-rtl.png",
        "plugins/magicline/images/icon.png",
        "plugins/placeholder/icons/hidpi/placeholder.png",
        "plugins/placeholder/icons/placeholder.png",
        "plugins/sourcedialog/icons/hidpi/sourcedialog-rtl.png",
        "plugins/sourcedialog/icons/hidpi/sourcedialog.png",
        "plugins/sourcedialog/icons/sourcedialog-rtl.png",
        "plugins/sourcedialog/icons/sourcedialog.png",
        "plugins/taoqtiimage/images/taoqtiimage.png",
        "plugins/taoqtimaths/images/taoqtimaths.png",
        "plugins/taoqtimedia/images/taoqtimedia.png",
        "plugins/taounderline/images/taounderline.png",
        "plugins/taoqtiinclude/images/taoqtiimage.png",
        "plugins/icons.png",
        "plugins/icons_hidpi.png"
    ]
}

**Comment by ssipasseuth** [comment]
other interesting metrics !
before : 1 406 files, totalling 5,1 MB
now : 72 files, totalling 1,1 MB

**Comment by ssipasseuth** [comment]
Sorry, I mistakenly removed the scss folder, it is restored now.

**Comment by krampstudio** [comment]
4MB of data plus the requests, it's gonna be better

**Pull request merged**
