### PR TITLE
tao-core-ui version bump

### PR DESCRIPTION
**Pull request by bartlomiejmarszal**
tao-core-ui version bump

https://oat-sa.atlassian.net/browse/CON-23

### CODE REVIEW

**Review by habemuscode — CHANGES_REQUESTED** [review]
Manifest bump required

**Comment by bartlomiejmarszal** [comment]
> Manifest bump required

We are merging to the integration branch so I'm not bumping the manifest version.

**Review by bziondik — APPROVED** [review]
Code review only

**Review by habemuscode — APPROVED** [review]
code review only

**Pull request merged**
