### PR TITLE
chore: bump version @oat-sa/tao-core-ui to 1.22.3

### PR DESCRIPTION
**Pull request by meefox**
bump version of @oat-sa/tao-core-ui

### CODE REVIEW

**Review by btamas — APPROVED** [review]

**Review by wazelin — DISMISSED** [review]

**Review by wazelin — CHANGES_REQUESTED** [review]
I can see the following error in the CI pipeline. Is everything OK there?

```
#10 5.472 npm ERR! code ENOLOCAL

#10 5.475 npm ERR! Could not install from "views/node_modules/raphael/eve@git:/github.com/adobe-webplatform/eve.git#eef80ed" as it does not contain a package.json file.
```

**Comment by btamas** [comment]
> I can see the following error in the CI pipeline. Is everything OK there?
> 
> ```
> #10 5.472 npm ERR! code ENOLOCAL
> 
> #10 5.475 npm ERR! Could not install from "views/node_modules/raphael/eve@git:/github.com/adobe-webplatform/eve.git#eef80ed" as it does not contain a package.json file.
> ```

I think yes, because it is a git repository and CI doesn't have git executable.

**Review by jsconan — APPROVED** [review]
Works fine.
Checked both with npm@6 and npm@7.

**Review by wazelin — CHANGES_REQUESTED** [review]
All right, but [here](https://github.com/oat-sa/tao-core/pull/2814/files#diff-598a3dd0ce9bb09748e55999126b42e2f38658bcec4dd2e4578023631f494d18R1843)'s an example of a PR that seems to be having a green build.

Could you please invest just a bit more time into checking what's going wrong with the build? It's important, as otherwise, you're going to have a failing build in develop, and eventually in all the other feature branches.

**Pull request merged**
