### PR TITLE
Hotfix: ADF-168 lock guzzlehttp versions

### PR DESCRIPTION
**Pull request by 404passionFruit**
Jira issue
https://oat-sa.atlassian.net/browse/ADF-168

Related PR
https://github.com/oat-sa/tao-community/pull/223

Deployed to integration playground (the link is in the ticket)

### CODE REVIEW

**Review by mike-ionut-mihai-sandu-tao — APPROVED** [review]
lgtm,  good job

**Review by habemuscode — APPROVED** [review]
LGFM Nice :D

**Review by bartlomiejmarszal — COMMENTED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

**Review by bartlomiejmarszal — APPROVED** [review]
Tested on playground

**Pull request merged**
